2023-03-29 00:17:44,544 INFO    MainThread:4212 [wandb_setup.py:_flush():76] Configure stats pid to 4212
2023-03-29 00:17:44,544 INFO    MainThread:4212 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-03-29 00:17:44,545 INFO    MainThread:4212 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\1.zadanie\src\wandb\settings
2023-03-29 00:17:44,545 INFO    MainThread:4212 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-29 00:17:44,545 INFO    MainThread:4212 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-03-29 00:17:44,545 INFO    MainThread:4212 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-29 00:17:44,545 INFO    MainThread:4212 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\1.zadanie\src\wandb\run-20230329_001744-tl70de8l\logs\debug.log
2023-03-29 00:17:44,546 INFO    MainThread:4212 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\1.zadanie\src\wandb\run-20230329_001744-tl70de8l\logs\debug-internal.log
2023-03-29 00:17:44,546 INFO    MainThread:4212 [wandb_init.py:init():546] calling init triggers
2023-03-29 00:17:44,546 INFO    MainThread:4212 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-03-29 00:17:44,546 INFO    MainThread:4212 [wandb_init.py:init():568] re-initializing run, found existing run on stack: mwdb6jd2
2023-03-29 00:17:44,549 INFO    MainThread:4212 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network_test1/mwdb6jd2
2023-03-29 00:17:44,549 INFO    MainThread:4212 [jupyter.py:save_history():445] not saving jupyter history
2023-03-29 00:17:44,550 INFO    MainThread:4212 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-29 00:17:44,550 INFO    MainThread:4212 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-03-29 00:17:44,550 INFO    MainThread:4212 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-29 00:17:44,550 INFO    MainThread:4212 [wandb_run.py:_restore():2066] restore
2023-03-29 00:17:44,550 INFO    MainThread:4212 [wandb_run.py:_restore():2072] restore done
2023-03-29 00:19:40,772 INFO    MainThread:4212 [wandb_init.py:init():602] starting backend
2023-03-29 00:19:40,772 INFO    MainThread:4212 [wandb_init.py:init():606] setting up manager
2023-03-29 00:19:40,777 INFO    MainThread:4212 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-29 00:19:40,781 INFO    MainThread:4212 [wandb_init.py:init():613] backend started and connected
2023-03-29 00:19:40,789 INFO    MainThread:4212 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-03-29 00:19:40,789 INFO    MainThread:4212 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-29 00:19:40,789 INFO    MainThread:4212 [wandb_init.py:init():701] updated telemetry
2023-03-29 00:19:40,837 INFO    MainThread:4212 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-29 00:19:41,334 WARNING MsgRouterThr:4212 [router.py:message_loop():77] message_loop has been closed
2023-03-29 00:19:41,343 WARNING MsgRouterThr:4212 [router.py:message_loop():77] message_loop has been closed
2023-03-29 00:19:41,884 WARNING MainThread:4212 [wandb_init.py:init():1165] interrupted
Traceback (most recent call last):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 744, in init
    result = run_init_handle.wait(
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "D:\Programs\Python\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "D:\Programs\Python\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
