2023-03-28 20:37:48,614 INFO    MainThread:14712 [wandb_setup.py:_flush():68] Configure stats pid to 14712
2023-03-28 20:37:48,614 INFO    MainThread:14712 [wandb_setup.py:_flush():68] Loading settings from C:\Users\andre\.config\wandb\settings
2023-03-28 20:37:48,614 INFO    MainThread:14712 [wandb_setup.py:_flush():68] Loading settings from D:\10.semester\NN\neural-networks\1.zadanie\src\wandb\settings
2023-03-28 20:37:48,614 INFO    MainThread:14712 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-28 20:37:48,614 INFO    MainThread:14712 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-28 20:37:48,615 INFO    MainThread:14712 [wandb_init.py:_log_setup():492] Logging user logs to D:\10.semester\NN\neural-networks\1.zadanie\src\wandb\run-20230328_203748-m626wgh1\logs\debug.log
2023-03-28 20:37:48,615 INFO    MainThread:14712 [wandb_init.py:_log_setup():493] Logging internal logs to D:\10.semester\NN\neural-networks\1.zadanie\src\wandb\run-20230328_203748-m626wgh1\logs\debug-internal.log
2023-03-28 20:37:48,616 INFO    MainThread:14712 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000163D0669900>
2023-03-28 20:37:48,616 INFO    MainThread:14712 [wandb_init.py:init():532] calling init triggers
2023-03-28 20:37:48,616 INFO    MainThread:14712 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-28 20:37:48,617 INFO    MainThread:14712 [wandb_init.py:init():554] re-initializing run, found existing run on stack: xb45ncqx
2023-03-28 20:37:48,620 INFO    MainThread:14712 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network/xb45ncqx
2023-03-28 20:37:48,620 INFO    MainThread:14712 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-28 20:37:48,620 INFO    MainThread:14712 [wandb_run.py:_restore():2066] restore
2023-03-28 20:37:48,621 INFO    MainThread:14712 [wandb_run.py:_restore():2072] restore done
2023-03-28 20:46:30,352 INFO    MainThread:14712 [wandb_init.py:init():588] starting backend
2023-03-28 20:46:30,352 INFO    MainThread:14712 [wandb_init.py:init():592] setting up manager
2023-03-28 20:46:30,356 INFO    MainThread:14712 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-28 20:46:30,358 INFO    MainThread:14712 [wandb_init.py:init():599] backend started and connected
2023-03-28 20:46:30,365 INFO    MainThread:14712 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-28 20:46:30,365 INFO    MainThread:14712 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-28 20:46:30,365 INFO    MainThread:14712 [wandb_init.py:init():687] updated telemetry
2023-03-28 20:46:30,416 INFO    MainThread:14712 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-28 20:46:33,095 WARNING MsgRouterThr:14712 [router.py:message_loop():77] message_loop has been closed
2023-03-28 20:46:33,108 WARNING MsgRouterThr:14712 [router.py:message_loop():77] message_loop has been closed
2023-03-28 20:46:33,467 WARNING MainThread:14712 [wandb_init.py:init():1154] interrupted
Traceback (most recent call last):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    wandb._assert_is_user_process()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 730, in init
    run._set_run_obj_offline(run_proto)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 273, in wait
    if on_probe:
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 120, in _get_and_clear
    self._wait_all = wait_all
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 116, in _wait
    self._abandoned = False
  File "D:\Programs\Python\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "D:\Programs\Python\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
