2023-04-11 23:49:11,183 INFO    MainThread:11920 [wandb_setup.py:_flush():76] Configure stats pid to 11920
2023-04-11 23:49:11,183 INFO    MainThread:11920 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-11 23:49:11,183 INFO    MainThread:11920 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-11 23:49:11,183 INFO    MainThread:11920 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-11 23:49:11,184 INFO    MainThread:11920 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-11 23:49:11,184 INFO    MainThread:11920 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-11 23:49:11,184 INFO    MainThread:11920 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230411_234911-dykhlofm\logs\debug.log
2023-04-11 23:49:11,185 INFO    MainThread:11920 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230411_234911-dykhlofm\logs\debug-internal.log
2023-04-11 23:49:11,185 INFO    MainThread:11920 [wandb_init.py:init():546] calling init triggers
2023-04-11 23:49:11,185 INFO    MainThread:11920 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-11 23:49:11,185 INFO    MainThread:11920 [wandb_init.py:init():568] re-initializing run, found existing run on stack: q1lovgfh
2023-04-11 23:49:11,187 INFO    MainThread:11920 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network-assgiment2/q1lovgfh
2023-04-11 23:49:11,187 INFO    MainThread:11920 [jupyter.py:save_history():445] not saving jupyter history
2023-04-11 23:49:11,188 INFO    MainThread:11920 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-11 23:49:11,188 INFO    MainThread:11920 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-04-11 23:49:11,188 INFO    MainThread:11920 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-11 23:49:11,188 INFO    MainThread:11920 [wandb_run.py:_restore():2066] restore
2023-04-11 23:49:11,189 INFO    MainThread:11920 [wandb_run.py:_restore():2072] restore done
2023-04-11 23:49:22,400 INFO    MainThread:11920 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-04-11 23:49:22,401 INFO    MainThread:11920 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-04-11 23:49:22,409 INFO    MainThread:11920 [wandb_run.py:_footer_sync_info():3380] logging synced files
2023-04-11 23:49:22,415 INFO    MainThread:11920 [wandb_init.py:init():602] starting backend
2023-04-11 23:49:22,415 INFO    MainThread:11920 [wandb_init.py:init():606] setting up manager
2023-04-11 23:49:22,418 INFO    MainThread:11920 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-11 23:49:22,421 INFO    MainThread:11920 [wandb_init.py:init():613] backend started and connected
2023-04-11 23:49:22,427 INFO    MainThread:11920 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-04-11 23:49:22,427 INFO    MainThread:11920 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-11 23:49:22,427 INFO    MainThread:11920 [wandb_init.py:init():701] updated telemetry
2023-04-11 23:49:22,480 INFO    MainThread:11920 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-11 23:49:24,097 INFO    MainThread:11920 [wandb_run.py:_on_init():2133] communicating current version
2023-04-11 23:49:24,316 INFO    MainThread:11920 [wandb_run.py:_on_init():2142] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-11 23:49:24,316 INFO    MainThread:11920 [wandb_init.py:init():789] starting run threads in backend
2023-04-11 23:49:24,489 INFO    MainThread:11920 [wandb_run.py:_console_start():2114] atexit reg
2023-04-11 23:49:24,490 INFO    MainThread:11920 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-04-11 23:49:24,490 INFO    MainThread:11920 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-04-11 23:49:24,490 INFO    MainThread:11920 [wandb_run.py:_redirect():2059] Redirects installed.
2023-04-11 23:49:24,490 INFO    MainThread:11920 [wandb_init.py:init():831] run started, returning control to user process
2023-04-11 23:49:24,491 INFO    MainThread:11920 [wandb_config.py:__setitem__():152] config set learning_rate = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000117546A9240>>
2023-04-11 23:49:24,491 INFO    MainThread:11920 [wandb_run.py:_config_callback():1251] config_cb learning_rate 0.001 None
2023-04-11 23:49:24,491 INFO    MainThread:11920 [wandb_config.py:__setitem__():152] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000117546A9240>>
2023-04-11 23:49:24,491 INFO    MainThread:11920 [wandb_run.py:_config_callback():1251] config_cb batch_size 32 None
2023-04-11 23:49:24,491 INFO    MainThread:11920 [wandb_config.py:__setitem__():152] config set epochs = 20 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000117546A9240>>
2023-04-11 23:49:24,492 INFO    MainThread:11920 [wandb_run.py:_config_callback():1251] config_cb epochs 20 None
2023-04-12 05:40:03,547 WARNING MsgRouterThr:11920 [router.py:message_loop():77] message_loop has been closed
