2023-04-10 15:55:38,672 INFO    StreamThr :3628 [internal.py:wandb_internal():87] W&B internal server running at pid: 3628, started at: 2023-04-10 15:55:38.670142
2023-04-10 15:55:38,673 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: status
2023-04-10 15:55:38,674 INFO    WriterThread:3628 [datastore.py:open_for_write():85] open: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\run-s5sdizny.wandb
2023-04-10 15:55:38,676 DEBUG   SenderThread:3628 [sender.py:send():336] send: header
2023-04-10 15:55:38,676 DEBUG   SenderThread:3628 [sender.py:send():336] send: run
2023-04-10 15:55:39,274 INFO    SenderThread:3628 [dir_watcher.py:__init__():219] watching files in: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files
2023-04-10 15:55:39,274 INFO    SenderThread:3628 [sender.py:_start_run_threads():1078] run started: s5sdizny with start time 1681134937.692658
2023-04-10 15:55:39,274 DEBUG   SenderThread:3628 [sender.py:send_request():363] send_request: summary_record
2023-04-10 15:55:39,275 INFO    SenderThread:3628 [sender.py:_save_file():1332] saving file wandb-summary.json with policy end
2023-04-10 15:55:39,276 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: check_version
2023-04-10 15:55:39,276 DEBUG   SenderThread:3628 [sender.py:send_request():363] send_request: check_version
2023-04-10 15:55:39,455 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: run_start
2023-04-10 15:55:39,475 DEBUG   HandlerThread:3628 [system_info.py:__init__():31] System info init
2023-04-10 15:55:39,475 DEBUG   HandlerThread:3628 [system_info.py:__init__():46] System info init done
2023-04-10 15:55:39,475 INFO    HandlerThread:3628 [system_monitor.py:start():183] Starting system monitor
2023-04-10 15:55:39,475 INFO    SystemMonitor:3628 [system_monitor.py:_start():147] Starting system asset monitoring threads
2023-04-10 15:55:39,475 INFO    HandlerThread:3628 [system_monitor.py:probe():204] Collecting system info
2023-04-10 15:55:39,479 INFO    SystemMonitor:3628 [interfaces.py:start():187] Started cpu monitoring
2023-04-10 15:55:39,479 INFO    SystemMonitor:3628 [interfaces.py:start():187] Started disk monitoring
2023-04-10 15:55:39,481 INFO    SystemMonitor:3628 [interfaces.py:start():187] Started gpu monitoring
2023-04-10 15:55:39,487 INFO    SystemMonitor:3628 [interfaces.py:start():187] Started memory monitoring
2023-04-10 15:55:39,508 DEBUG   HandlerThread:3628 [system_info.py:probe():195] Probing system
2023-04-10 15:55:39,508 INFO    SystemMonitor:3628 [interfaces.py:start():187] Started network monitoring
2023-04-10 15:55:39,510 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:39,511 DEBUG   HandlerThread:3628 [system_info.py:_probe_git():180] Probing git
2023-04-10 15:55:39,600 DEBUG   HandlerThread:3628 [system_info.py:_probe_git():188] Probing git done
2023-04-10 15:55:39,600 DEBUG   HandlerThread:3628 [system_info.py:probe():240] Probing system done
2023-04-10 15:55:39,600 DEBUG   HandlerThread:3628 [system_monitor.py:probe():213] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.10.7', 'heartbeatAt': '2023-04-10T13:55:39.508196', 'startedAt': '2023-04-10T13:55:25.676199', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': '2.zadanie/src/second_assignment.ipynb', 'root': 'D:/10.semester/NN/neural-networks', 'git': {'remote': 'https://github.com/martinkukucka/neural-networks.git', 'commit': '3b2b88353701b54c301f6e3f709b9cb1bb04ac7c'}, 'email': 'andrejbelak0@gmail.com', 'host': 'AndysLAPTOP', 'username': 'andre', 'executable': 'd:\\programs\\pyhtonprograms\\bettscrapper\\venv\\scripts\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2592.0, 'min': 0.0, 'max': 2592.0}, 'cpu_freq_per_core': [{'current': 2592.0, 'min': 0.0, 'max': 2592.0}], 'disk': {'total': 683.5937461853027, 'used': 434.02019119262695}, 'gpu': 'GeForce GTX 1660 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'GeForce GTX 1660 Ti', 'memory_total': 6442450944}], 'memory': {'total': 15.912220001220703}}
2023-04-10 15:55:39,600 INFO    HandlerThread:3628 [system_monitor.py:probe():214] Finished collecting system info
2023-04-10 15:55:39,600 INFO    HandlerThread:3628 [system_monitor.py:probe():217] Publishing system info
2023-04-10 15:55:39,600 DEBUG   HandlerThread:3628 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-10 15:55:39,601 DEBUG   HandlerThread:3628 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-10 15:55:39,602 INFO    HandlerThread:3628 [system_monitor.py:probe():219] Finished publishing system info
2023-04-10 15:55:39,602 DEBUG   SenderThread:3628 [sender.py:send():336] send: files
2023-04-10 15:55:39,602 INFO    SenderThread:3628 [sender.py:_save_file():1332] saving file wandb-metadata.json with policy now
2023-04-10 15:55:39,619 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: stop_status
2023-04-10 15:55:39,619 DEBUG   SenderThread:3628 [sender.py:send_request():363] send_request: stop_status
2023-04-10 15:55:39,809 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: get_summary
2023-04-10 15:55:39,850 DEBUG   SenderThread:3628 [sender.py:send():336] send: telemetry
2023-04-10 15:55:39,850 DEBUG   SenderThread:3628 [sender.py:send():336] send: telemetry
2023-04-10 15:55:39,850 DEBUG   SenderThread:3628 [sender.py:send():336] send: run
2023-04-10 15:55:40,212 INFO    SenderThread:3628 [sender.py:send_run():955] updated run: s5sdizny
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: telemetry
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: config
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: config
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: config
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: telemetry
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: telemetry
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: files
2023-04-10 15:55:40,213 INFO    SenderThread:3628 [sender.py:_save_file():1332] saving file model-best.h5 with policy live
2023-04-10 15:55:40,213 DEBUG   SenderThread:3628 [sender.py:send():336] send: telemetry
2023-04-10 15:55:40,282 INFO    wandb-upload_0:3628 [upload_job.py:push():138] Uploaded file C:\Users\andre\AppData\Local\Temp\tmp0ci0rgqjwandb\gd578h8x-wandb-metadata.json
2023-04-10 15:55:40,289 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\config.yaml
2023-04-10 15:55:40,289 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_created():278] file/dir created: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\wandb-summary.json
2023-04-10 15:55:40,289 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_created():278] file/dir created: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\requirements.txt
2023-04-10 15:55:40,290 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_created():278] file/dir created: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\wandb-metadata.json
2023-04-10 15:55:41,548 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:42,786 DEBUG   SenderThread:3628 [sender.py:send():336] send: files
2023-04-10 15:55:42,786 INFO    SenderThread:3628 [sender.py:_save_file():1332] saving file media\graph\graph_summary_892f05c00f865c0dbd0a.graph.json with policy now
2023-04-10 15:55:42,787 DEBUG   SenderThread:3628 [sender.py:send_request():363] send_request: summary_record
2023-04-10 15:55:42,788 INFO    SenderThread:3628 [sender.py:_save_file():1332] saving file wandb-summary.json with policy end
2023-04-10 15:55:43,321 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\wandb-summary.json
2023-04-10 15:55:43,321 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_created():278] file/dir created: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\media\graph\graph_summary_892f05c00f865c0dbd0a.graph.json
2023-04-10 15:55:43,322 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_created():278] file/dir created: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:43,323 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_created():278] file/dir created: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\media
2023-04-10 15:55:43,323 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_created():278] file/dir created: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\media\graph
2023-04-10 15:55:43,422 INFO    wandb-upload_0:3628 [upload_job.py:push():138] Uploaded file C:\Users\andre\AppData\Local\Temp\tmp0ci0rgqjwandb\crdy1pmq-media/graph/graph_summary_892f05c00f865c0dbd0a.graph.json
2023-04-10 15:55:43,636 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:43,856 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: status_report
2023-04-10 15:55:45,361 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:45,724 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:47,406 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:47,809 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:49,054 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: status_report
2023-04-10 15:55:49,426 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:49,875 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:51,465 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:51,955 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:53,485 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:54,056 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:54,100 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: status_report
2023-04-10 15:55:54,631 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: stop_status
2023-04-10 15:55:54,632 DEBUG   SenderThread:3628 [sender.py:send_request():363] send_request: stop_status
2023-04-10 15:55:55,499 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:56,113 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:57,534 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:55:58,204 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:55:59,103 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: status_report
2023-04-10 15:55:59,541 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:56:00,258 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:01,558 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:56:02,321 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:03,590 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:56:04,194 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: status_report
2023-04-10 15:56:04,378 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:05,613 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:56:06,464 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:07,644 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:56:08,520 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:09,349 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: status_report
2023-04-10 15:56:09,631 ERROR   SenderThread:3628 [internal_api.py:execute():246] 409 response executing GraphQL.
2023-04-10 15:56:09,631 ERROR   SenderThread:3628 [internal_api.py:execute():247] {"errors":[{"message":"run neural-netwok-nn/neural-network-assgiment2/s5sdizny was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-10 15:56:09,653 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: stop_status
2023-04-10 15:56:09,674 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:56:10,697 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:11,227 ERROR   SenderThread:3628 [internal_api.py:execute():246] 409 response executing GraphQL.
2023-04-10 15:56:11,227 ERROR   SenderThread:3628 [internal_api.py:execute():247] {"errors":[{"message":"run neural-netwok-nn/neural-network-assgiment2/s5sdizny was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-10 15:56:11,698 INFO    Thread-32 :3628 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_155525-s5sdizny\files\output.log
2023-04-10 15:56:12,741 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:13,922 ERROR   SenderThread:3628 [internal_api.py:execute():246] 409 response executing GraphQL.
2023-04-10 15:56:13,922 ERROR   SenderThread:3628 [internal_api.py:execute():247] {"errors":[{"message":"run neural-netwok-nn/neural-network-assgiment2/s5sdizny was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-10 15:56:13,923 INFO    SenderThread:3628 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-04-10 15:56:14,710 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: keepalive
2023-04-10 15:56:14,791 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:16,829 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:18,833 ERROR   SenderThread:3628 [internal_api.py:execute():246] 409 response executing GraphQL.
2023-04-10 15:56:18,834 ERROR   SenderThread:3628 [internal_api.py:execute():247] {"errors":[{"message":"run neural-netwok-nn/neural-network-assgiment2/s5sdizny was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-10 15:56:18,870 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:19,752 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: keepalive
2023-04-10 15:56:20,921 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:22,993 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:24,794 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: keepalive
2023-04-10 15:56:25,056 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:27,137 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:27,986 ERROR   SenderThread:3628 [internal_api.py:execute():246] 409 response executing GraphQL.
2023-04-10 15:56:27,987 ERROR   SenderThread:3628 [internal_api.py:execute():247] {"errors":[{"message":"run neural-netwok-nn/neural-network-assgiment2/s5sdizny was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-04-10 15:56:29,198 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:29,846 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: keepalive
2023-04-10 15:56:31,283 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:33,360 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
2023-04-10 15:56:34,898 DEBUG   HandlerThread:3628 [handler.py:handle_request():144] handle_request: keepalive
2023-04-10 15:56:35,454 ERROR   gpu       :3628 [interfaces.py:monitor():141] Failed to sample metric: Not Supported
